### ISSUE TITLE
Incorrect behavior for iw as a text object action

### ISSUE THREAD

**Issue by robcsi** [gcmt/wildfire.vim#19]
Hi,

Nice plugin here, in some ways better that vim-expand-region.

I've added iw as an action myself locally, and it works, although it doesn't work well in this case

```
if (method () == "some text")
```

When standing on word text, pressing once selects the word, but pressing twice it selects text") and not the content of quotes.

Cheers,
robcsi

**Comment by jackywu** [comment]
may I ask for how to add 'iw' to select a word ? could you show me the configuration ? @robcsi
