### ISSUE TITLE
Q: how to select outer parens?

### ISSUE THREAD

**Issue by mfiano** [gcmt/wildfire.vim#23]
How can I use this to select the parentheses as well, when used with a Lisp language?

**Comment by gcmt** [comment]
If you need to sporadically select outer parentheses you can just hit `a)` once you have selected th `i)` text object. Otherwise you can add the `a)` text object to candidates: 
```vim
cal wildfire#triggers#Add("<SPACE>", {
  \ "*" : split("i' i\" i) i] i}"),
  \ "lisp" : split("i) a)"),
\ })
```
