### ISSUE TITLE
Q: how can i select the text between " | "?

### ISSUE THREAD

**Issue by KeqiZeng** [gcmt/wildfire.vim#26]
Hey, thanks for providing this plug. It's so awesome.
I always want to select the text between " | ", when i use vim-table-mode.  I try to add  "i|" and "i<Bar>"  in g:wildfire_objects, but both can't work.
Can you help me? thank you so much.

**Comment by gcmt** [comment]
Using the text object "i|" seems to be fixed now but I don't understand what you mean by simply using "i" as a text object.

**Comment by KeqiZeng** [comment]
> Using the text object "i|" seems to be fixed now but I don't understand what you mean by simply using "i" as a text object.

Oh, sorry, I wrote it wrongly. It is not "i", but "i<Bar>". I tried it because vim-table-mode provide a text-object "i<Bar>".
Well, i will try "i|" again tomorrow. Thanks a lot!

**Comment by KeqiZeng** [comment]
> > Using the text object "i|" seems to be fixed now but I don't understand what you mean by simply using "i" as a text object.
> 
> Oh, sorry, I wrote it wrongly. It is not "i", but "i". I tried it because vim-table-mode provide a text-object "i".
> Well, i will try "i|" again tomorrow. Thanks a lot!

I mean "i Bar mit "<>" ". it doesn't seem to be displayed correctly

**Comment by KeqiZeng** [comment]
I have "i|" tried. When i open neovim, there is no error message anymore. But it seems also can't work.
this is my config for wildfire:
```
let g:wildfire_objects = {
		\ "*" : ["i'", "a'", 'i"','a"', "i)", "a)", "i]", "a]", "i}", "a}", "i>", "a>", "it", "at", "i|"],
    \ }
```
The  word under cursor is between "|", just like markdown-table, and i press enter, but nothing happened.

**Comment by gcmt** [comment]
I just tried the example tables from the project readme and it works even with nvim. Remember that you're still required to activate table mode first with `:TableModeEanble`, otherwise the `vim-table-mode` text objects won't be available.

**Comment by KeqiZeng** [comment]
> I just tried the example tables from the project readme and it works even with nvim. Remember that you're still required to activate table mode first with `:TableModeEanble`, otherwise the `vim-table-mode` text objects won't be available.

You're right, in table-mode it works so good. Thanks for answering my question and have a nice day or night.
