### ISSUE TITLE
how to make wildfire.vim to select a word under cursor ?

### ISSUE THREAD

**Issue by jackywu** [gcmt/wildfire.vim#32]
how to make wildfire.vim to select a word under cursor ?
I add this config `      vim.g.wildfire_objects = { "iw", "i'", 'i"', "i)", "i]", "i}", "ip", "it" } `, but seems doesn't works.

**Comment by gcmt** [comment]
I'm not familiar with the syntax you just used.. Seems to be working fine for me if I initialize the objects like this:

``let g:wildfire_objects = ["iw", "i'", 'i"', "i)", "i]", "i}", "ip", "it"]``

**Comment by lorefnon** [comment]
The original example uses lua for neovim. It does work, but we need to ensure that the global variable is assigned before the plugin loads.

This is what most traditional vim plugins follow, but is different from the increasingly common pattern followed by lua plugins where we require the plugin first and then configure it.
