### ISSUE TITLE
how to disable wildfire in specific filetype

### ISSUE THREAD

**Issue by AndreGeng** [gcmt/wildfire.vim#33]
how to disable wildfire key `<CR>` mapping temporarily in specific filetype.  
In my case, I am using [oil.nvm](https://github.com/stevearc/oil.nvim), it use `<CR>` to open file under cursor, I want to disable wildfire `<CR>` mapping for buffers with filetype "oil"

**Comment by gcmt** [comment]
Something like this should do the work I think
```
let g:wildfire_objects = {
	\ "*" : ["i'", 'i"', "i)", "i]", "i}", "ip", "it"],
	\ "oil" : [],
\}
```

**Comment by AndreGeng** [comment]
tried it, `<CR>` still not working as expected in oil buffer.
`:map <CR>` shows following result
![image](https://github.com/gcmt/wildfire.vim/assets/3634890/9570471d-5fa8-41ae-a653-d3305478ddc5)

**Comment by gcmt** [comment]
Unfortunately I can't really try wildfire.vim on neovim right now but let's see..

From your screenshot (first line) it seems that `<CR>` is working neither as wildfire.vim or oil.vim mapping. Am I correct? Wildfire.vim disable itself when the `&buftype` is not empty by doing a non-recursive mapping of `g:wildfire_fuel_map` to itself (see https://github.com/gcmt/wildfire.vim/blob/master/plugin/wildfire.vim#L76). Try removing that line to see if that's the culprit
